GET https://www.ttvn.nl/api/action/getallactions HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDkyNDM4OTksImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTYwOTMzMDI5OSwidXNlcmlkIjoiMzE5ODA0OCIsImRhdGFiYXNlIjoidHRlc3QiLCJyb2xlIjoiQlMsVEUsQUQiLCJmaXJzdG5hbWUiOiJXaW0iLCJsYXN0bmFtZSI6IktpZWxlbiJ9.eRfxgIjnyF9YK6-F-0v2BEphofMI2yrqxrWy6eL0bRY
//Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDkyNDQzMDgsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTY0MDc4MDMwOCwidXNlcmlkIjoid2ltIiwiZGF0YWJhc2UiOiJ0dGVzdCIsInJvbGUiOiJUUixURSIsImZpcnN0bmFtZSI6IldpbSIsImxhc3RuYW1lIjoia2llbGVuIn0.crM-ldRUIC7GVStyc0vgw2nNF7Poas_UNqLnfg4AkwM
